name: Python Tests

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout repository
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pwd
        ls -a
        pip install -r .github/workflows/requirements.txt 
    
    - name: Run tests
      run: |
        python -m pytest test/